console.log("project on console");
var firstname="Elaine";
var secondname="Rose";
var thirdname="Rodrigues";
var fullname=firstname.concat(secondname);
var finalname=fullname.concat(thirdname);
console.log(finalname);
var a=2;
var b=9;
var add=a+b;
console.log(a,b,add);